name: example
description: A project that showcases usage of openapi_retrofit_generator
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  # ==========================================================================
  #
  # Direct pub.dev dependencies
  #
  # ==========================================================================
  dio: ^5.9.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  retrofit: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.0
  json_serializable: ^6.11.0
  retrofit_generator: ^10.1.0
  openapi_retrofit_generator: ^2.0.0
  flutter_lints: ^6.0.0
